/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pruebas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;

/**
 *
 * @author scast
 */
public class VentanaMedicoPrueba extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMedicoPrueba
     */
    int xMouse,

    /**
     * Creates new form VentanaMedicoPrueba
     */
    yMouse, 

    /**
     * Creates new form VentanaMedicoPrueba
     */
    x, 

    /**
     * Creates new form VentanaMedicoPrueba
     */
    y;

    public VentanaMedicoPrueba() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelBase.setLayout(new BorderLayout());
        listBuscarEnfermedades.setCellRenderer(new SelectedListCellRenderer());
        listMedicamentos.setCellRenderer(new SelectedListCellRenderer());
        panelBase.add(panelPacientesDelDia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPacientesDelDia = new javax.swing.JPanel();
        labelENombreEnfermedad3 = new javax.swing.JLabel();
        scrollListaMedicamentos5 = new javax.swing.JScrollPane();
        listBuscarEnfermedades2 = new javax.swing.JList<>();
        labelENombreEnfermedad4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        labelENombreEnfermedad5 = new javax.swing.JLabel();
        labelENombreEnfermedad6 = new javax.swing.JLabel();
        labelENombreEnfermedad7 = new javax.swing.JLabel();
        panelBuscarPaciente = new javax.swing.JPanel();
        textBuscarEnfermedad1 = new javax.swing.JTextField();
        buttonBuscarEnfermedad1 = new javax.swing.JButton();
        buttonBorrarEnfermedad1 = new javax.swing.JButton();
        labelENombreEnfermedad1 = new javax.swing.JLabel();
        buttonBuscarEnfermedad2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrollListaMedicamentos4 = new javax.swing.JScrollPane();
        listBuscarEnfermedades1 = new javax.swing.JList<>();
        labelENombreEnfermedad2 = new javax.swing.JLabel();
        panelBuscarEnfermedad = new javax.swing.JPanel();
        buttonBorrarEnfermedad = new javax.swing.JButton();
        buttonBuscarEnfermedad = new javax.swing.JButton();
        scrollListaMedicamentos1 = new javax.swing.JScrollPane();
        listBuscarEnfermedades = new javax.swing.JList<>();
        textBuscarEnfermedad = new javax.swing.JTextField();
        labelBuscarEnfermedad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelENombreEnfermedad = new javax.swing.JLabel();
        scrollListaMedicamentos3 = new javax.swing.JScrollPane();
        listMedicamentos = new javax.swing.JList<>();
        labelNombreMedicamento = new javax.swing.JLabel();
        labelDosisRecomendada2 = new javax.swing.JLabel();
        labelDosisDiaria2 = new javax.swing.JLabel();
        labelListaEMedicamentos2 = new javax.swing.JLabel();
        labelEnfermedadContagiosa2 = new javax.swing.JLabel();
        labelEnfermedadesRelacionadas2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEnfermedadesRel = new javax.swing.JTextArea();
        panelBuscarMedicamento1 = new javax.swing.JPanel();
        buttonBorrar1 = new javax.swing.JButton();
        buttonBuscar1 = new javax.swing.JButton();
        scrollListaMedicamentos2 = new javax.swing.JScrollPane();
        listBuscarMedicamentos = new javax.swing.JList<>();
        textBuscar1 = new javax.swing.JTextField();
        labelBuscarEnfermedad1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelListaMedicamentos3 = new javax.swing.JLabel();
        labelEnfermedadesRelacionadas3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        labelListaMedicamentos4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        labelListaMedicamentos5 = new javax.swing.JLabel();
        labelListaMedicamentos6 = new javax.swing.JLabel();
        panelFondo = new javax.swing.JPanel();
        panelBarraSuperior = new javax.swing.JPanel();
        panelMinimizar = new javax.swing.JPanel();
        labelMinimizar = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();
        panelCerrarSesion = new javax.swing.JPanel();
        labelCerrarSesion = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        buttonPaciente1 = new javax.swing.JButton();
        buttonEnfermedad = new javax.swing.JButton();
        buttonMedicamento = new javax.swing.JButton();
        buttonPaciente = new javax.swing.JButton();
        panelBase = new javax.swing.JPanel();

        panelPacientesDelDia.setBackground(new java.awt.Color(81, 81, 81));
        panelPacientesDelDia.setPreferredSize(new java.awt.Dimension(896, 512));
        panelPacientesDelDia.setRequestFocusEnabled(false);
        panelPacientesDelDia.setVerifyInputWhenFocusTarget(false);

        labelENombreEnfermedad3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad3.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad3.setText("Fecha : viernes 4 de noviembre de 2022");
        labelENombreEnfermedad3.setPreferredSize(new java.awt.Dimension(420, 20));

        listBuscarEnfermedades2.setBackground(new java.awt.Color(71, 71, 71));
        listBuscarEnfermedades2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        listBuscarEnfermedades2.setForeground(new java.awt.Color(204, 204, 204));
        listBuscarEnfermedades2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12345678901234567890123456789012", "Item 2", "Item 3", "Item 4", "Item 5", "no hay " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBuscarEnfermedades2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBuscarEnfermedades2ValueChanged(evt);
            }
        });
        scrollListaMedicamentos5.setViewportView(listBuscarEnfermedades2);

        labelENombreEnfermedad4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad4.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad4.setText("Enfermos a visitar");
        labelENombreEnfermedad4.setPreferredSize(new java.awt.Dimension(420, 20));

        jScrollPane6.setPreferredSize(new java.awt.Dimension(242, 20));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(71, 71, 71));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea5.setRows(6);
        jTextArea5.setTabSize(4);
        jTextArea5.setBorder(null);
        jTextArea5.setPreferredSize(new java.awt.Dimension(252, 20));
        jScrollPane6.setViewportView(jTextArea5);

        labelENombreEnfermedad5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad5.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad5.setText("paco antonio");
        labelENombreEnfermedad5.setPreferredSize(new java.awt.Dimension(420, 20));

        labelENombreEnfermedad6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad6.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad6.setText("Síntomas");
        labelENombreEnfermedad6.setPreferredSize(new java.awt.Dimension(420, 20));

        labelENombreEnfermedad7.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad7.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad7.setText("Habitación 161");
        labelENombreEnfermedad7.setPreferredSize(new java.awt.Dimension(420, 20));

        javax.swing.GroupLayout panelPacientesDelDiaLayout = new javax.swing.GroupLayout(panelPacientesDelDia);
        panelPacientesDelDia.setLayout(panelPacientesDelDiaLayout);
        panelPacientesDelDiaLayout.setHorizontalGroup(
            panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelENombreEnfermedad3, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                        .addGroup(panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollListaMedicamentos5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(labelENombreEnfermedad4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelENombreEnfermedad6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacientesDelDiaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelENombreEnfermedad5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelENombreEnfermedad7, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        panelPacientesDelDiaLayout.setVerticalGroup(
            panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelENombreEnfermedad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(labelENombreEnfermedad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPacientesDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPacientesDelDiaLayout.createSequentialGroup()
                        .addComponent(labelENombreEnfermedad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(labelENombreEnfermedad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(labelENombreEnfermedad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollListaMedicamentos5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        panelBuscarPaciente.setBackground(new java.awt.Color(61, 61, 61));
        panelBuscarPaciente.setPreferredSize(new java.awt.Dimension(896, 512));
        panelBuscarPaciente.setRequestFocusEnabled(false);
        panelBuscarPaciente.setVerifyInputWhenFocusTarget(false);

        textBuscarEnfermedad1.setBackground(new java.awt.Color(71, 71, 71));
        textBuscarEnfermedad1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        textBuscarEnfermedad1.setForeground(new java.awt.Color(204, 204, 204));
        textBuscarEnfermedad1.setText("12345678A");
        textBuscarEnfermedad1.setToolTipText("");
        textBuscarEnfermedad1.setBorder(null);
        textBuscarEnfermedad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBuscarEnfermedad1KeyPressed(evt);
            }
        });

        buttonBuscarEnfermedad1.setBackground(new java.awt.Color(71, 71, 71));
        buttonBuscarEnfermedad1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBuscarEnfermedad1.setForeground(new java.awt.Color(204, 204, 204));
        buttonBuscarEnfermedad1.setText("Buscar");
        buttonBuscarEnfermedad1.setBorderPainted(false);
        buttonBuscarEnfermedad1.setFocusPainted(false);
        buttonBuscarEnfermedad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedad1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedad1MousePressed(evt);
            }
        });

        buttonBorrarEnfermedad1.setBackground(new java.awt.Color(71, 71, 71));
        buttonBorrarEnfermedad1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBorrarEnfermedad1.setForeground(new java.awt.Color(204, 204, 204));
        buttonBorrarEnfermedad1.setText("Añadir historial");
        buttonBorrarEnfermedad1.setBorderPainted(false);
        buttonBorrarEnfermedad1.setFocusPainted(false);

        labelENombreEnfermedad1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad1.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad1.setText("Escribe el DNI del paciente (12345678A):");
        labelENombreEnfermedad1.setPreferredSize(new java.awt.Dimension(420, 20));

        buttonBuscarEnfermedad2.setBackground(new java.awt.Color(71, 71, 71));
        buttonBuscarEnfermedad2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBuscarEnfermedad2.setForeground(new java.awt.Color(204, 204, 204));
        buttonBuscarEnfermedad2.setText("Borrar");
        buttonBuscarEnfermedad2.setBorderPainted(false);
        buttonBuscarEnfermedad2.setFocusPainted(false);
        buttonBuscarEnfermedad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedad2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedad2MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(81, 81, 81));

        listBuscarEnfermedades1.setBackground(new java.awt.Color(71, 71, 71));
        listBuscarEnfermedades1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        listBuscarEnfermedades1.setForeground(new java.awt.Color(204, 204, 204));
        listBuscarEnfermedades1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12345678901234567890123456789012", "Item 2", "Item 3", "Item 4", "Item 5", "no hay " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBuscarEnfermedades1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBuscarEnfermedades1ValueChanged(evt);
            }
        });
        scrollListaMedicamentos4.setViewportView(listBuscarEnfermedades1);

        labelENombreEnfermedad2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad2.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad2.setText("paco antonio (1245678A)");
        labelENombreEnfermedad2.setPreferredSize(new java.awt.Dimension(420, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollListaMedicamentos4)
                    .addComponent(labelENombreEnfermedad2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelENombreEnfermedad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollListaMedicamentos4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBuscarPacienteLayout = new javax.swing.GroupLayout(panelBuscarPaciente);
        panelBuscarPaciente.setLayout(panelBuscarPacienteLayout);
        panelBuscarPacienteLayout.setHorizontalGroup(
            panelBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarPacienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelENombreEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBuscarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonBuscarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonBuscarEnfermedad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(buttonBorrarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBuscarPacienteLayout.setVerticalGroup(
            panelBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarPacienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelENombreEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBuscarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarEnfermedad1)
                    .addComponent(buttonBuscarEnfermedad2)
                    .addComponent(buttonBorrarEnfermedad1))
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBuscarEnfermedad.setBackground(new java.awt.Color(61, 61, 61));
        panelBuscarEnfermedad.setPreferredSize(new java.awt.Dimension(896, 512));
        panelBuscarEnfermedad.setRequestFocusEnabled(false);
        panelBuscarEnfermedad.setVerifyInputWhenFocusTarget(false);

        buttonBorrarEnfermedad.setBackground(new java.awt.Color(71, 71, 71));
        buttonBorrarEnfermedad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBorrarEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        buttonBorrarEnfermedad.setText("Borrar");
        buttonBorrarEnfermedad.setBorderPainted(false);
        buttonBorrarEnfermedad.setFocusPainted(false);

        buttonBuscarEnfermedad.setBackground(new java.awt.Color(71, 71, 71));
        buttonBuscarEnfermedad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBuscarEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        buttonBuscarEnfermedad.setText("Buscar");
        buttonBuscarEnfermedad.setBorderPainted(false);
        buttonBuscarEnfermedad.setFocusPainted(false);
        buttonBuscarEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBuscarEnfermedadMousePressed(evt);
            }
        });

        listBuscarEnfermedades.setBackground(new java.awt.Color(71, 71, 71));
        listBuscarEnfermedades.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        listBuscarEnfermedades.setForeground(new java.awt.Color(204, 204, 204));
        listBuscarEnfermedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12345678901234567890123456789012", "Item 2", "Item 3", "Item 4", "Item 5", "no hay " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBuscarEnfermedades.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBuscarEnfermedadesValueChanged(evt);
            }
        });
        scrollListaMedicamentos1.setViewportView(listBuscarEnfermedades);

        textBuscarEnfermedad.setBackground(new java.awt.Color(71, 71, 71));
        textBuscarEnfermedad.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        textBuscarEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        textBuscarEnfermedad.setText("12345678901234567890");
        textBuscarEnfermedad.setToolTipText("");
        textBuscarEnfermedad.setBorder(null);
        textBuscarEnfermedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBuscarEnfermedadKeyPressed(evt);
            }
        });

        labelBuscarEnfermedad.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelBuscarEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        labelBuscarEnfermedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarEnfermedad.setText("Resultados de la búsqueda");
        labelBuscarEnfermedad.setPreferredSize(new java.awt.Dimension(280, 20));

        jPanel1.setBackground(new java.awt.Color(81, 81, 81));

        labelENombreEnfermedad.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelENombreEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        labelENombreEnfermedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelENombreEnfermedad.setText("Enfermedad: nombre de la enfermedad");
        labelENombreEnfermedad.setPreferredSize(new java.awt.Dimension(420, 20));

        listMedicamentos.setBackground(new java.awt.Color(71, 71, 71));
        listMedicamentos.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        listMedicamentos.setForeground(new java.awt.Color(204, 204, 204));
        listMedicamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "12345678901234567890123456789012", "Item 2", "Item 3", "Item 4", "Item 5", "no hay " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMedicamentos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMedicamentosValueChanged(evt);
            }
        });
        scrollListaMedicamentos3.setViewportView(listMedicamentos);

        labelNombreMedicamento.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelNombreMedicamento.setForeground(new java.awt.Color(204, 204, 204));
        labelNombreMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreMedicamento.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

        labelDosisRecomendada2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelDosisRecomendada2.setForeground(new java.awt.Color(204, 204, 204));
        labelDosisRecomendada2.setText("Dosis recomendada: xxxxxx");

        labelDosisDiaria2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelDosisDiaria2.setForeground(new java.awt.Color(204, 204, 204));
        labelDosisDiaria2.setText("Dosis diaria: xxxxxxxx");
        labelDosisDiaria2.setPreferredSize(new java.awt.Dimension(280, 20));

        labelListaEMedicamentos2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelListaEMedicamentos2.setForeground(new java.awt.Color(204, 204, 204));
        labelListaEMedicamentos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaEMedicamentos2.setText("Lista de medicamentos");

        labelEnfermedadContagiosa2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelEnfermedadContagiosa2.setForeground(new java.awt.Color(0, 192, 0));
        labelEnfermedadContagiosa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnfermedadContagiosa2.setText("Enfermedad no contagiosa");

        labelEnfermedadesRelacionadas2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelEnfermedadesRelacionadas2.setForeground(new java.awt.Color(204, 204, 204));
        labelEnfermedadesRelacionadas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnfermedadesRelacionadas2.setText("Enfermedades relacionadas");

        textEnfermedadesRel.setEditable(false);
        textEnfermedadesRel.setBackground(new java.awt.Color(71, 71, 71));
        textEnfermedadesRel.setColumns(20);
        textEnfermedadesRel.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        textEnfermedadesRel.setForeground(new java.awt.Color(204, 204, 204));
        textEnfermedadesRel.setRows(6);
        textEnfermedadesRel.setTabSize(4);
        textEnfermedadesRel.setBorder(null);
        textEnfermedadesRel.setPreferredSize(new java.awt.Dimension(252, 132));
        jScrollPane2.setViewportView(textEnfermedadesRel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelENombreEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEnfermedadContagiosa2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelListaEMedicamentos2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollListaMedicamentos3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(labelDosisRecomendada2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(labelDosisDiaria2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addComponent(labelEnfermedadesRelacionadas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelENombreEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnfermedadContagiosa2))
                .addGap(24, 24, 24)
                .addComponent(labelListaEMedicamentos2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollListaMedicamentos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNombreMedicamento)
                        .addGap(32, 32, 32)
                        .addComponent(labelDosisRecomendada2)
                        .addGap(32, 32, 32)
                        .addComponent(labelDosisDiaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(labelEnfermedadesRelacionadas2)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout panelBuscarEnfermedadLayout = new javax.swing.GroupLayout(panelBuscarEnfermedad);
        panelBuscarEnfermedad.setLayout(panelBuscarEnfermedadLayout);
        panelBuscarEnfermedadLayout.setHorizontalGroup(
            panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEnfermedadLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollListaMedicamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarEnfermedadLayout.createSequentialGroup()
                        .addGroup(panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelBuscarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(textBuscarEnfermedad, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBuscarEnfermedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBorrarEnfermedad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarEnfermedadLayout.setVerticalGroup(
            panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEnfermedadLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarEnfermedad))
                .addGap(16, 16, 16)
                .addGroup(panelBuscarEnfermedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrarEnfermedad)
                    .addComponent(labelBuscarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(scrollListaMedicamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBuscarMedicamento1.setBackground(new java.awt.Color(61, 61, 61));
        panelBuscarMedicamento1.setPreferredSize(new java.awt.Dimension(896, 512));
        panelBuscarMedicamento1.setRequestFocusEnabled(false);
        panelBuscarMedicamento1.setVerifyInputWhenFocusTarget(false);

        buttonBorrar1.setBackground(new java.awt.Color(71, 71, 71));
        buttonBorrar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBorrar1.setForeground(new java.awt.Color(204, 204, 204));
        buttonBorrar1.setText("Borrar");
        buttonBorrar1.setBorderPainted(false);
        buttonBorrar1.setFocusPainted(false);

        buttonBuscar1.setBackground(new java.awt.Color(71, 71, 71));
        buttonBuscar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        buttonBuscar1.setForeground(new java.awt.Color(204, 204, 204));
        buttonBuscar1.setText("Buscar");
        buttonBuscar1.setBorderPainted(false);
        buttonBuscar1.setFocusPainted(false);
        buttonBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBuscar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonBuscar1MousePressed(evt);
            }
        });

        listBuscarMedicamentos.setBackground(new java.awt.Color(71, 71, 71));
        listBuscarMedicamentos.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        listBuscarMedicamentos.setForeground(new java.awt.Color(204, 204, 204));
        listBuscarMedicamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "sd", "s", "d", "fdgh", "jkl", " ", "c" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBuscarMedicamentos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listBuscarMedicamentosValueChanged(evt);
            }
        });
        scrollListaMedicamentos2.setViewportView(listBuscarMedicamentos);

        textBuscar1.setBackground(new java.awt.Color(71, 71, 71));
        textBuscar1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        textBuscar1.setForeground(new java.awt.Color(204, 204, 204));
        textBuscar1.setText("werref");
        textBuscar1.setToolTipText("");
        textBuscar1.setBorder(null);
        textBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textBuscar1KeyPressed(evt);
            }
        });

        labelBuscarEnfermedad1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelBuscarEnfermedad1.setForeground(new java.awt.Color(204, 204, 204));
        labelBuscarEnfermedad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarEnfermedad1.setText("Resultados de la búsqueda");
        labelBuscarEnfermedad1.setPreferredSize(new java.awt.Dimension(280, 20));

        jPanel2.setBackground(new java.awt.Color(81, 81, 81));

        labelListaMedicamentos3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelListaMedicamentos3.setForeground(new java.awt.Color(204, 204, 204));
        labelListaMedicamentos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaMedicamentos3.setText("Enfermedades");

        labelEnfermedadesRelacionadas3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelEnfermedadesRelacionadas3.setForeground(new java.awt.Color(204, 204, 204));
        labelEnfermedadesRelacionadas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnfermedadesRelacionadas3.setText("Efectos secunadarios");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(242, 20));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(71, 71, 71));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea2.setRows(6);
        jTextArea2.setTabSize(4);
        jTextArea2.setBorder(null);
        jTextArea2.setPreferredSize(new java.awt.Dimension(252, 20));
        jScrollPane3.setViewportView(jTextArea2);

        labelListaMedicamentos4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelListaMedicamentos4.setForeground(new java.awt.Color(204, 204, 204));
        labelListaMedicamentos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaMedicamentos4.setText("Posibles alergias");

        jScrollPane4.setPreferredSize(new java.awt.Dimension(242, 20));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(71, 71, 71));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea3.setRows(6);
        jTextArea3.setTabSize(4);
        jTextArea3.setBorder(null);
        jTextArea3.setPreferredSize(new java.awt.Dimension(252, 20));
        jScrollPane4.setViewportView(jTextArea3);

        jScrollPane5.setPreferredSize(new java.awt.Dimension(242, 20));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(71, 71, 71));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea4.setRows(6);
        jTextArea4.setTabSize(4);
        jTextArea4.setBorder(null);
        jTextArea4.setPreferredSize(new java.awt.Dimension(252, 20));
        jScrollPane5.setViewportView(jTextArea4);

        labelListaMedicamentos5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelListaMedicamentos5.setForeground(new java.awt.Color(204, 204, 204));
        labelListaMedicamentos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaMedicamentos5.setText("Nombre del medicamento");

        labelListaMedicamentos6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        labelListaMedicamentos6.setForeground(new java.awt.Color(204, 204, 204));
        labelListaMedicamentos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaMedicamentos6.setText("que cura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelListaMedicamentos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelEnfermedadesRelacionadas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelListaMedicamentos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelListaMedicamentos6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelListaMedicamentos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelListaMedicamentos5)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelListaMedicamentos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelListaMedicamentos6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelListaMedicamentos4)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelEnfermedadesRelacionadas3)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout panelBuscarMedicamento1Layout = new javax.swing.GroupLayout(panelBuscarMedicamento1);
        panelBuscarMedicamento1.setLayout(panelBuscarMedicamento1Layout);
        panelBuscarMedicamento1Layout.setHorizontalGroup(
            panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarMedicamento1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollListaMedicamentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarMedicamento1Layout.createSequentialGroup()
                        .addGroup(panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelBuscarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(textBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBuscar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBorrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscarMedicamento1Layout.setVerticalGroup(
            panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarMedicamento1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar1))
                .addGap(16, 16, 16)
                .addGroup(panelBuscarMedicamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrar1)
                    .addComponent(labelBuscarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(scrollListaMedicamentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(768, 618));

        panelFondo.setBackground(new java.awt.Color(90, 90, 90));
        panelFondo.setPreferredSize(new java.awt.Dimension(0, 0));

        panelBarraSuperior.setBackground(new java.awt.Color(51, 51, 51));
        panelBarraSuperior.setPreferredSize(new java.awt.Dimension(0, 0));
        panelBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMouseDragged(evt);
            }
        });
        panelBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraSuperiorMousePressed(evt);
            }
        });

        panelMinimizar.setBackground(new java.awt.Color(51, 51, 51));
        panelMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelMinimizarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelMinimizarFocusLost(evt);
            }
        });
        panelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMinimizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMinimizarMouseReleased(evt);
            }
        });

        labelMinimizar.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        labelMinimizar.setForeground(new java.awt.Color(204, 204, 204));
        labelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizar.setText("-");
        labelMinimizar.setMaximumSize(new java.awt.Dimension(14, 30));
        labelMinimizar.setMinimumSize(new java.awt.Dimension(14, 30));
        labelMinimizar.setPreferredSize(new java.awt.Dimension(14, 30));
        labelMinimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                labelMinimizarFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panelMinimizarLayout = new javax.swing.GroupLayout(panelMinimizar);
        panelMinimizar.setLayout(panelMinimizarLayout);
        panelMinimizarLayout.setHorizontalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        panelMinimizarLayout.setVerticalGroup(
            panelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelSalir.setBackground(new java.awt.Color(51, 51, 51));
        panelSalir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelSalirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelSalirFocusLost(evt);
            }
        });
        panelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelSalirMouseReleased(evt);
            }
        });

        labelSalir.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(204, 204, 204));
        labelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalir.setText("x");

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelCerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        panelCerrarSesion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelCerrarSesionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                panelCerrarSesionFocusLost(evt);
            }
        });
        panelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseReleased(evt);
            }
        });

        labelCerrarSesion.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        labelCerrarSesion.setForeground(new java.awt.Color(204, 204, 204));
        labelCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrarSesion.setText("·");
        labelCerrarSesion.setMaximumSize(new java.awt.Dimension(14, 30));
        labelCerrarSesion.setMinimumSize(new java.awt.Dimension(14, 30));
        labelCerrarSesion.setPreferredSize(new java.awt.Dimension(14, 30));
        labelCerrarSesion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                labelCerrarSesionFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarSesionLayout = new javax.swing.GroupLayout(panelCerrarSesion);
        panelCerrarSesion.setLayout(panelCerrarSesionLayout);
        panelCerrarSesionLayout.setHorizontalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
        panelCerrarSesionLayout.setVerticalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBarraSuperiorLayout = new javax.swing.GroupLayout(panelBarraSuperior);
        panelBarraSuperior.setLayout(panelBarraSuperiorLayout);
        panelBarraSuperiorLayout.setHorizontalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraSuperiorLayout.createSequentialGroup()
                .addComponent(panelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(752, 752, 752)
                .addComponent(panelMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBarraSuperiorLayout.setVerticalGroup(
            panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu.setPreferredSize(new java.awt.Dimension(0, 0));

        buttonPaciente1.setBackground(new java.awt.Color(68, 68, 68));
        buttonPaciente1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        buttonPaciente1.setForeground(new java.awt.Color(204, 204, 204));
        buttonPaciente1.setText("Pacientes del día");
        buttonPaciente1.setBorderPainted(false);
        buttonPaciente1.setFocusPainted(false);
        buttonPaciente1.setPreferredSize(new java.awt.Dimension(140, 26));
        buttonPaciente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPaciente1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPaciente1MousePressed(evt);
            }
        });

        buttonEnfermedad.setBackground(new java.awt.Color(68, 68, 68));
        buttonEnfermedad.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        buttonEnfermedad.setForeground(new java.awt.Color(204, 204, 204));
        buttonEnfermedad.setText("Enfermedades");
        buttonEnfermedad.setBorderPainted(false);
        buttonEnfermedad.setFocusPainted(false);
        buttonEnfermedad.setPreferredSize(new java.awt.Dimension(140, 26));
        buttonEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnfermedadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonEnfermedadMousePressed(evt);
            }
        });
        buttonEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnfermedadActionPerformed(evt);
            }
        });

        buttonMedicamento.setBackground(new java.awt.Color(68, 68, 68));
        buttonMedicamento.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        buttonMedicamento.setForeground(new java.awt.Color(204, 204, 204));
        buttonMedicamento.setText("Medicamentos");
        buttonMedicamento.setBorderPainted(false);
        buttonMedicamento.setFocusPainted(false);
        buttonMedicamento.setPreferredSize(new java.awt.Dimension(140, 26));
        buttonMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMedicamentoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMedicamentoMousePressed(evt);
            }
        });

        buttonPaciente.setBackground(new java.awt.Color(68, 68, 68));
        buttonPaciente.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        buttonPaciente.setForeground(new java.awt.Color(204, 204, 204));
        buttonPaciente.setText("Historial pacientes");
        buttonPaciente.setBorderPainted(false);
        buttonPaciente.setFocusPainted(false);
        buttonPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPacienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPacienteMousePressed(evt);
            }
        });
        buttonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(buttonEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(buttonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        panelBase.setBackground(new java.awt.Color(61, 61, 61));
        panelBase.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addComponent(panelBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSalirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelSalirFocusGained

    }//GEN-LAST:event_panelSalirFocusGained

    private void panelSalirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelSalirFocusLost

    }//GEN-LAST:event_panelSalirFocusLost

    private void panelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseClicked

    }//GEN-LAST:event_panelSalirMouseClicked

    private void panelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseEntered
        panelSalir.setBackground(new Color(192, 0, 0));
    }//GEN-LAST:event_panelSalirMouseEntered

    private void panelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseExited
        panelSalir.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_panelSalirMouseExited

    private void panelSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseReleased
        System.exit(0);
    }//GEN-LAST:event_panelSalirMouseReleased

    private void panelBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraSuperiorMouseDragged

    private void panelBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraSuperiorMousePressed

    private void labelMinimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelMinimizarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMinimizarFocusGained

    private void panelMinimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelMinimizarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMinimizarFocusGained

    private void panelMinimizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelMinimizarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMinimizarFocusLost

    private void panelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMinimizarMouseClicked

    private void panelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseEntered
        panelMinimizar.setBackground(new Color(71, 71, 71));
    }//GEN-LAST:event_panelMinimizarMouseEntered

    private void panelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseExited
        panelMinimizar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_panelMinimizarMouseExited

    private void panelMinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMinimizarMousePressed

    private void panelMinimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMinimizarMouseReleased
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_panelMinimizarMouseReleased

    private void buttonEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnfermedadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEnfermedadMouseClicked

    private void buttonEnfermedadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnfermedadMousePressed
        panelBase.removeAll();
        panelBase.add(panelBuscarEnfermedad);

        panelBase.revalidate();
        panelBase.repaint();
    }//GEN-LAST:event_buttonEnfermedadMousePressed

    private void buttonEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEnfermedadActionPerformed

    private void buttonPaciente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPaciente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPaciente1MouseClicked

    private void buttonPaciente1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPaciente1MousePressed
        panelBase.removeAll();
        panelBase.add(panelPacientesDelDia);
        panelBase.revalidate();
        panelBase.repaint();
    }//GEN-LAST:event_buttonPaciente1MousePressed

    private void buttonMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMedicamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicamentoMouseClicked

    private void buttonMedicamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMedicamentoMousePressed
        panelBase.removeAll();
        panelBase.add(panelBuscarMedicamento1);
        panelBase.revalidate();
        panelBase.repaint();
    }//GEN-LAST:event_buttonMedicamentoMousePressed

    private void buttonPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPacienteMouseClicked

    private void buttonPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPacienteMousePressed
        panelBase.removeAll();
        panelBase.add(panelBuscarPaciente);
        panelBase.revalidate();
        panelBase.repaint();
    }//GEN-LAST:event_buttonPacienteMousePressed

    private void buttonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPacienteActionPerformed

    private void labelCerrarSesionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelCerrarSesionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCerrarSesionFocusGained

    private void panelCerrarSesionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelCerrarSesionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCerrarSesionFocusGained

    private void panelCerrarSesionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelCerrarSesionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCerrarSesionFocusLost

    private void panelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCerrarSesionMouseClicked

    private void panelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseEntered
        panelCerrarSesion.setBackground(new Color(71, 71, 71));
    }//GEN-LAST:event_panelCerrarSesionMouseEntered

    private void panelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseExited
        panelCerrarSesion.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_panelCerrarSesionMouseExited

    private void panelCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCerrarSesionMousePressed

    private void panelCerrarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCerrarSesionMouseReleased

    private void buttonBuscarEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedadMouseClicked

    private void buttonBuscarEnfermedadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedadMousePressed

    private void textBuscarEnfermedadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarEnfermedadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscarEnfermedad.doClick();
        }
    }//GEN-LAST:event_textBuscarEnfermedadKeyPressed

    private void listBuscarEnfermedadesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBuscarEnfermedadesValueChanged
        labelENombreEnfermedad.setText("Enfermedad: " + listBuscarEnfermedades.getSelectedValue());
    }//GEN-LAST:event_listBuscarEnfermedadesValueChanged

    private void listMedicamentosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMedicamentosValueChanged
        labelNombreMedicamento.setText(listMedicamentos.getSelectedValue() + " ");
    }//GEN-LAST:event_listMedicamentosValueChanged

    private void buttonBuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscar1MouseClicked

    private void buttonBuscar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscar1MousePressed

    private void listBuscarMedicamentosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBuscarMedicamentosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listBuscarMedicamentosValueChanged

    private void textBuscar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscar1KeyPressed

    private void textBuscarEnfermedad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarEnfermedad1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarEnfermedad1KeyPressed

    private void buttonBuscarEnfermedad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedad1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedad1MouseClicked

    private void buttonBuscarEnfermedad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedad1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedad1MousePressed

    private void buttonBuscarEnfermedad2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedad2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedad2MouseClicked

    private void buttonBuscarEnfermedad2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBuscarEnfermedad2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarEnfermedad2MousePressed

    private void listBuscarEnfermedades1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBuscarEnfermedades1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listBuscarEnfermedades1ValueChanged

    private void listBuscarEnfermedades2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listBuscarEnfermedades2ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listBuscarEnfermedades2ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMedicoPrueba().setVisible(true);
            }
        });
    }

    public class SelectedListCellRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (isSelected) {
                c.setBackground(new Color(91, 91, 91));
                c.setForeground(new Color(204, 204, 204));

            }
            return c;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrar1;
    private javax.swing.JButton buttonBorrarEnfermedad;
    private javax.swing.JButton buttonBorrarEnfermedad1;
    private javax.swing.JButton buttonBuscar1;
    private javax.swing.JButton buttonBuscarEnfermedad;
    private javax.swing.JButton buttonBuscarEnfermedad1;
    private javax.swing.JButton buttonBuscarEnfermedad2;
    private javax.swing.JButton buttonEnfermedad;
    private javax.swing.JButton buttonMedicamento;
    private javax.swing.JButton buttonPaciente;
    private javax.swing.JButton buttonPaciente1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel labelBuscarEnfermedad;
    private javax.swing.JLabel labelBuscarEnfermedad1;
    private javax.swing.JLabel labelCerrarSesion;
    private javax.swing.JLabel labelDosisDiaria2;
    private javax.swing.JLabel labelDosisRecomendada2;
    private javax.swing.JLabel labelENombreEnfermedad;
    private javax.swing.JLabel labelENombreEnfermedad1;
    private javax.swing.JLabel labelENombreEnfermedad2;
    private javax.swing.JLabel labelENombreEnfermedad3;
    private javax.swing.JLabel labelENombreEnfermedad4;
    private javax.swing.JLabel labelENombreEnfermedad5;
    private javax.swing.JLabel labelENombreEnfermedad6;
    private javax.swing.JLabel labelENombreEnfermedad7;
    private javax.swing.JLabel labelEnfermedadContagiosa2;
    private javax.swing.JLabel labelEnfermedadesRelacionadas2;
    private javax.swing.JLabel labelEnfermedadesRelacionadas3;
    private javax.swing.JLabel labelListaEMedicamentos2;
    private javax.swing.JLabel labelListaMedicamentos3;
    private javax.swing.JLabel labelListaMedicamentos4;
    private javax.swing.JLabel labelListaMedicamentos5;
    private javax.swing.JLabel labelListaMedicamentos6;
    private javax.swing.JLabel labelMinimizar;
    private javax.swing.JLabel labelNombreMedicamento;
    private javax.swing.JLabel labelSalir;
    private javax.swing.JList<String> listBuscarEnfermedades;
    private javax.swing.JList<String> listBuscarEnfermedades1;
    private javax.swing.JList<String> listBuscarEnfermedades2;
    private javax.swing.JList<String> listBuscarMedicamentos;
    private javax.swing.JList<String> listMedicamentos;
    private javax.swing.JPanel panelBarraSuperior;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelBuscarEnfermedad;
    private javax.swing.JPanel panelBuscarMedicamento1;
    private javax.swing.JPanel panelBuscarPaciente;
    private javax.swing.JPanel panelCerrarSesion;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMinimizar;
    private javax.swing.JPanel panelPacientesDelDia;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JScrollPane scrollListaMedicamentos1;
    private javax.swing.JScrollPane scrollListaMedicamentos2;
    private javax.swing.JScrollPane scrollListaMedicamentos3;
    private javax.swing.JScrollPane scrollListaMedicamentos4;
    private javax.swing.JScrollPane scrollListaMedicamentos5;
    private javax.swing.JTextField textBuscar1;
    private javax.swing.JTextField textBuscarEnfermedad;
    private javax.swing.JTextField textBuscarEnfermedad1;
    private javax.swing.JTextArea textEnfermedadesRel;
    // End of variables declaration//GEN-END:variables
}
