/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uv.vista;

/**
 *
 * @author sergv
 */
public class MedicoVisitar extends javax.swing.JFrame {

    /**
     * Creates new form MedicoVisitar
     */
    public MedicoVisitar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        scrollPacientes = new javax.swing.JScrollPane();
        listPacientes = new javax.swing.JList<>();
        labelPacientes = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelNombreMedico = new javax.swing.JLabel();
        labelNPacientes = new javax.swing.JLabel();
        labelListaPacientes = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        textADescripción = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listPacientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPacientes.setViewportView(listPacientes);

        panelPrincipal.add(scrollPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 700, 150));

        labelPacientes.setText("Pacientes");
        panelPrincipal.add(labelPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        labelDescripcion.setText("Descripcion del paciente");
        panelPrincipal.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        labelNombreMedico.setText("Nombre del medico");
        panelPrincipal.add(labelNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        labelNPacientes.setText("Nº Pacientes: XX");
        panelPrincipal.add(labelNPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        labelListaPacientes.setText("Lista de pacientes");
        panelPrincipal.add(labelListaPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labelFecha.setText("dd-mm-aaaa");
        panelPrincipal.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        textADescripción.setColumns(20);
        textADescripción.setRows(5);
        scrollDescripcion.setViewportView(textADescripción);

        panelPrincipal.add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 700, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoVisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoVisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoVisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoVisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoVisitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelListaPacientes;
    private javax.swing.JLabel labelNPacientes;
    private javax.swing.JLabel labelNombreMedico;
    private javax.swing.JLabel labelPacientes;
    private javax.swing.JList<String> listPacientes;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JScrollPane scrollPacientes;
    private javax.swing.JTextArea textADescripción;
    // End of variables declaration//GEN-END:variables
}
